# Generated by Django 5.1 on 2025-01-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%y/%m/%d')),
                ('name', models.CharField(max_length=50)),
                ('jop_description', models.TextField()),
                ('full_name', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('about_me', models.TextField()),
                ('work_completed', models.PositiveIntegerField(default=0)),
                ('year_experience', models.PositiveIntegerField(default=0)),
                ('total_client', models.PositiveIntegerField(default=0)),
                ('award_won', models.PositiveIntegerField(default=0)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=255)),
                ('telegram', models.CharField(blank=True, max_length=255)),
                ('youtube', models.CharField(blank=True, max_length=255)),
                ('tiktok', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
