# Generated by Django 5.1 on 2025-01-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%y/%m/%d')),
                ('title', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
