# Generated by Django 5.1 on 2025-01-16 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cv',
            field=models.FileField(default=django.utils.timezone.now, upload_to='file/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
